apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio

---
apiVersion: v1
kind: Namespace
metadata:
  name: testns
  labels:
    name: testns
    istio-injection: enabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd